runtime: php55
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js
  
- url: /images
  static_dir: images
  
- url: /paddlegame
  script: index.html
  
- url: /
  script: helloworld.php